### ISSUE TITLE
Sorting of pts causes Chrome to display incorrect CEA-608 embedded captions

### ISSUE THREAD

**Issue by ianwelsh** [videojs/mux.js#100]
I was having this issue, https://github.com/videojs/videojs-contrib-hls/issues/761.

But when I remove the following code from line 190 of caption_stream.js:

```
this.captionPackets_.sort(function(a, b) {
    return a.pts - b.pts;
  });
```

The problem resolves itself. Tested in Chrome, Firefox, and Safari. 

Can someone explain why this code is necessary? Is this code OK to take out without breaking something else?
If not, are there any workarounds I can implement?

**Comment by ianwelsh** [comment]
I believe this is due to Chrome having an unstable Array.prototype.sort() implementation (https://bugs.chromium.org/p/v8/issues/detail?id=90), whereas Firefox and Safari have stable implementations.

### Example
**Pre-sort:**
```
[{"type":0,"pts":8353875960,"ccData":8320},
{"type":0,"pts":8353875960,"ccData":37925},
{"type":0,"pts":8353875960,"ccData":38061}]
```
**Post-sort in Chrome:**
```
[{"type":0,"pts":8353875960,"ccData":37925},
{"type":0,"pts":8353875960,"ccData":38061},
{"type":0,"pts":8353875960,"ccData":8320}]
```
**Post-sort in Firefox:**
```
[{"type":0,"pts":8353875960,"ccData":8320},
{"type":0,"pts":8353875960,"ccData":37925},
{"type":0,"pts":8353875960,"ccData":38061}]
```

Any reason why I shouldn't take out the sort? Are there any conditions where the caption packets would get unsorted?

**Comment by dmlap** [comment]
@ianwelsh if the video is encoded with b-frames, caption packets will arrive out-of-order and so it's important to resort them before display. Good find about the unstable sort() though! I suspect you're right and that is causing the problem. We should find some way to disambiguate our comparator so that there are no equivalent caption packets during the sorting.
