### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by iongion** [videojs/mux.js#102]
I have two binary streams, a h264 and aac file, that were extracted from a mpeg-ts segment.
Is it possible to use mux.js to create an mp4 using these, or even directly mpeg-ts ?
My plan is to read the mpeg-ts as bytearray and then use a ts demuxer to extract the aac and h264 streams, and finally, using mux.js for boxing them together in a large mp4 ?

But, is it possible ? :+1:

**Comment by smilemd** [comment]
+1, is it possible to extract from multiple mpeg-ts segments into a large mp4 file?

**Comment by dmlap** [comment]
@iongion it is but I haven't heard that before so we may not add explicit documentation for it unless it comes up again. I think you would feed your raw data into the [H264](https://github.com/videojs/mux.js/blob/58ab20a8b45e51397a328fa9bd91230c667529d2/lib/codecs/h264.js) and [ADTS](https://github.com/videojs/mux.js/blob/58ab20a8b45e51397a328fa9bd91230c667529d2/lib/codecs/adts.js) streams and then build up the rest of the mp4 output pipeline similarly to how it's done in [the transmuxer](https://github.com/videojs/mux.js/blob/58ab20a8b45e51397a328fa9bd91230c667529d2/lib/mp4/transmuxer.js#L952) today.

@smilemd the output of the TS to MP4 transmuxing is a series of MP4 fragments. If you simply concatenate them together, you have a large MP4 file that will play in any reasonably-modern MP4 video player :)
