### ISSUE TITLE
Issues with streams that have PES packets split between segments

### ISSUE THREAD

**Issue by ntadej** [videojs/mux.js#105]
Our streams have audio PES packets split between segments - one starts at the end of one .ts file and continues into the next. Calling flush on audio in ElementaryStream (https://github.com/ntadej/mux.js/blob/master/lib/m2ts/m2ts.js#L434) causes player to stall for a brief moment (throbber is shown). Commenting this line out fixes all playback issues with our streams that I reported with new videojs-contrib-hls. (it breaks seeking though)

I'm not familiar enough with mux.js to fix this on my own but I'm happy to provide you any assistance needed to do so. You should already have access to our steams.

**Comment by mjneil** [comment]
Sorry for the long time to resolve this, but this should be fixed by #157 which is now released
