### ISSUE TITLE
Problems with multiple track audio.

### ISSUE THREAD

**Issue by londono** [videojs/mux.js#106]
Hi, first good job with this mux.js. Second, I have a chunk of 10 sec of .ts with 1 Video track and 3 Audio tracks and I am using your debug site. I have one error : mux.js line 4090 Uncaught TypeError: Cannot read property '0' of undefined.  The same kind of video with 1 video 1 Audio is working just fine. Can you help me?, please!

**Comment by BrandonOCasey** [comment]
Can you post a sample of the TS that is giving you an issue?

**Comment by londono** [comment]
1 Video track and 3 Audio tracks 
[segments1.zip](https://github.com/videojs/mux.js/files/407044/segments1.zip)

**Comment by londono** [comment]
My own mistake in the creation of the segment. Now I can read the segment TS but the audio output seems to be a mix of two streams audio.  I got a video TS 1 video and 2 audios (when the audio is just the same stream but repeated).  How I can  manipule the tracks??. here is my segment 

[testTwoAudios.zip](https://github.com/videojs/mux.js/files/413520/testTwoAudios.zip)

**Comment by synologic** [comment]
Same issue here (actually coming from hls.js). If multiple audio tracks are present, all are sent to the transmuxer, resulting in garbled audio or even video crash (in chrome). Would be helpful to have an audio selection based on the PMT content, or at least filter all but one audio track (which i did in my case).

**Comment by cronello** [comment]
Same issue with multiple audio tracks when using videojs-contrib-hls.
At `ElementaryStream` is just one buffer for video, audio, so when multiple audio track came all audio is pushed into the same audio buffer.
Just for my workaround, I push into audio buffer just the first audio track, by PID from PMT table
at `ElementaryStream.push pes function` I replace `case StreamTypes.ADTS_STREAM_TYPE` content by:
```javascript
case StreamTypes.ADTS_STREAM_TYPE:
            // take care about the first audio track and not mixing multiple audio 
            // into one output stream
            if (!audio.pid) {
                audio.pid = data.pid;
            }
            if (audio.pid === data.pid) {
                stream = audio;
                streamType = 'audio';
                break;
            }
            // ignor other audio track
            return;
```

I'll be good, to have some API for selecting audio track

**Comment by imbcmdth** [comment]
@cronello This change would be great to have a PR for. Thanks for looking into this.

We don't have any plans to support multiple audio tracks in a segment but we definitely should still pull out a single track (even if multiple are present) correctly.

**Comment by mjneil** [comment]
v4.2.2 of mux.js now uses the first audio and video track found in the PMT. I am closing this issue for now. Please re-open or open a new issue if you experience any issues with multiple tracks
