### ISSUE TITLE
done/data event not rised in transmuxer object

### ISSUE THREAD

**Issue by peyoh** [videojs/mux.js#117]
Hi, 
```
var fs = require('fs');



var mp2t = require('./lib/m2ts'),
    codecs = require('./lib/codecs'),
    aac = require('./lib/aac'),
    flv = require('./lib/flv'),
    id3Generator = require('./test/utils/id3-generator'),
    mp4 = require('./lib/mp4'),
    mp4AudioProperties = require('./lib/mp4/transmuxer').AUDIO_PROPERTIES,
    mp4VideoProperties = require('./lib/mp4/transmuxer').VIDEO_PROPERTIES,
    Transmuxer = mp4.Transmuxer,
    FlvTransmuxer = flv.Transmuxer;


var segments = [];
var transmuxer = new Transmuxer();

transmuxer.on('data', function(segment) {
    console.log("Data event");
    segments.push(segment);
});
transmuxer.on('done', function(segment) {
    console.log("Done event");
    segments.push(segment);
});
fs.readFile('aac.bin',  function(err, contents) {
    console.log("Source file data");
    console.log("Buffer size " + contents.byteLength);

    let uarray = new Uint8Array(contents);
    console.log(typeof uarray);
    transmuxer.push(uarray);
});
```

I've tested with two MPEG-TS files (video and audio pids):
aac.bin - only AAC audio
aac_mp2.bin - AAC and MP2 audio

[The files are accessable here](https://drive.google.com/folderview?id=0B7KCfFBKrvsNV1VBeFVkNkdrMWc&usp=sharing)

But no events are raised after the .push call. 

That's the reason I've asked in [#116](https://github.com/videojs/mux.js/issues/116)

What can be the reason?

**Comment by mjneil** [comment]
Add `transmuxer.flush();` directly after `transmuxer.push(uarray);`. The transmuxer will emit `data` and `done` once it receives those events from the `CoalesceStream` which does not emit them until it reaches its `flush` process.
