### ISSUE TITLE
BaseMediaDecodeTime and seeking

### ISSUE THREAD

**Issue by dmlap** [videojs/mux.js#12]
If you seek before buffering any content, how is BaseMediaDecodeTime calculated?

**Comment by imbcmdth** [comment]
I think there are only two possibilities in streams without discontinuities:
* Always load the first segment to anchor the DTSs in the transmuxer.
* Act as we do during a discontinuity-seek and set timestampOffset to the start of the expected segment before appending data if there was nothing ever loaded into the buffer.

**Comment by dmlap** [comment]
My preference is the latter. You?

**Comment by imbcmdth** [comment]
The question then becomes:

How do we detect the condition that "nothing was ever loaded into the buffer" the buffer could be empty because of MSE's "garbage collection" type algorithm or because of Flash's "blow away the work on seek".

**Comment by dmlap** [comment]
I think we need a mechanism on the transmuxers that is roughly equivalent to `timestampOffset` on a source buffer. If it's never modified, we use the first pushed segment to anchor the DTS. If `timestampOffset` is modified, we adjust the DTS anchor appropriately. Once an anchor has been established, it stays in effect unless `timestampOffset` is changed.

**Comment by imbcmdth** [comment]
We already have a mechanism to reset the baseMediaDecodeTime's starting DTS - we recreate the transmuxer!

The question is how do we, from HLS, know whether or not to set the `timestampOffset` on a sourceBuffer before appending data. This issue is really a larger thing than just mux.js. (In fact, the solution won't live here at all I think.)

**Comment by imbcmdth** [comment]
We now handle timestampOffset inside the transmuxer using baseMediaDecodeTime. Closing this as it no longer applies.
