### ISSUE TITLE
on("data") is called with segment with no data

### ISSUE THREAD

**Issue by farhumaglass** [videojs/mux.js#180]
Hi all,
The following [URL](https://yvpub-bucket001-west.west.edge.storage-yahoo.jp/contents/yvpub-content-7250ed5f778e7f0b8b16ff0977996232/hls/fe6021b88db5bb0064292b04daf4de45/500k/output_00001.ts) returns only one sgement with `initData`. `data` remains empty array.
The file is downloaded as part of DASH video with at [yahoo.co.jp](https://headlines.yahoo.co.jp/ted?a=20150608-00001699-ted).

**Comment by forbesjo** [comment]
Could you provide more information about your use case? Are you using mux.js directly or loading an HLS source through videojs-http-streaming/videojs-contrib-hls? If you are using videojs-http-streaming/videojs-contrib-hls could you please provide a jsbin test page https://jsbin.com/gejugat/edit?html,output
