### ISSUE TITLE
remuxed video play at IE11 or Edge, show afterimage

### ISSUE THREAD

**Issue by purpletortoise-choi** [videojs/mux.js#187]
After i do remux ts to mp4 at Edge or IE 11 (windows10).
I try to play remuxed video. 

Remuxed video play well, but show afterimage when backward or forward seeking.

![afterimageissue](https://user-images.githubusercontent.com/11069488/38021242-4e747544-32b7-11e8-8131-4fb78c1eab3e.gif)

Sample Url is 'https://video-dev.github.io/streams/x36xhzz/url_6/url_846/193039199_mp4_h264_aac_hq_7.ts'

Please check it.
Thanks

**Comment by mjneil** [comment]
Edge and IE11 seem to have some problems with their MSE implementation. I've reported a similar issue to Microsoft here https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14600417/

**Comment by elasim** [comment]
safari browser has same issue
