### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by joeyparrish** [videojs/mux.js#259]
The tops of your source files say:

```js
/**
 * mux.js
 *
 * Copyright (c) 2016 Brightcove
 * All rights reserved.
 */
```

But your LICENSE file says:

```
Copyright 2015 Brightcove

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
```

If this is intended to be licensed under Apache 2.0, can you please fix the tops of your source files to unambiguously state this instead of "all rights reserved"?  What is currently in LICENSE would make a good header in the source files.

And could you please update LICENSE to contain the [full text of the Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0.txt), which contains the actual license terms in their full form?

Thanks!

**Comment by gkatsev** [comment]
Oops, yes, it's all licensed as apache 2.0

**Comment by gkatsev** [comment]
Sorry it's taken so long, we have a PR ready in #262
