### ISSUE TITLE
No license header in minified bundle

### ISSUE THREAD

**Issue by joeyparrish** [videojs/mux.js#342]
Hi everyone,

As you're probably aware, we're using mux.js in Shaka Player.  When pushing Shaka Player releases through internal channels at Google, there are certain policy checks that happen, and mux.min.js always fails a check for a license header.

I know there's no reason you should have to comply with somebody else's policies, but would there be any objection to me sending a PR to insert your license header at the top of the minified bundles?

Thanks!

**Comment by gkatsev** [comment]
Publish as 5.6.4. Thanks @joeyparrish.
