### ISSUE TITLE
Is it possible to mux a stream?

### ISSUE THREAD

**Issue by TroyDota** [videojs/mux.js#363]
Consider a buffer coming via a websocket 
-> the buffer is not a complete file (ie not a full hls segment)

**Comment by gkatsev** [comment]
It's definitely possible, but I think you basically need to segment it on the client side. We don't currently support raw h264 (there's a PR but we're not sure we can maintain it).

**Comment by TroyDota** [comment]
Segment on client side?
I segmented on server side and sent one second segments up and it worked fine, when i sent segments with varying length the remuxer worked correctly but the MediaSource rejected the remuxed data.

**Comment by TroyDota** [comment]
^ such as hls_time at 1s (where all segments are exactly 1s) worked fine but segmenting video at 0.1s failed as the segment function returned video of length 0.12s and 0.13. If i did not set a GOP size the remuxer still accepts but the media source rejects as the segments are now not exactly 1 seconds on the hls example.
