### ISSUE TITLE
Is there a way to transmux WEBM into MP4 using mux.js 

### ISSUE THREAD

**Issue by kenluck2001** [videojs/mux.js#371]
I would like to know if there is support for transmuxing WEBM video container into MP4 format.
If there is a support, please provide example of how to use the lib to achieve this goal.

Thanks so much.

**Comment by brandonocasey** [comment]
This is currently no support for transmuxing web to mp4. Currently we only support mpegts with x264/aac data and adts with aac data transmuxing to fragmented mp4

**Comment by kenluck2001** [comment]
Thanks so much for the concise answer. This issue will be closed.
