### ISSUE TITLE
Consider parsing AAC raw_data_block

### ISSUE THREAD

**Issue by imbcmdth** [videojs/mux.js#4]
Without a user-provided codec parameter we can't know whether an AAC audio track is AAC-LC or HE-AAC without parsing the actual ADTS frame to check for a `fil_element` specifying an extension payload that contains `SBR` data. (So called "implicit signaling")

## Problem:
We need to know the codec to use in order to set up an audio `sourceBuffer` to correctly decode an audio track.

## Solution 1
Allow users to specify a `codec=` after the `video/m2ts` string to the `addSourceBuffer` function in `videojs-contrib-media-sources`

### Pros
* Keeps the muxer as simple as possible
* Can support more/future codecs without changes to any code
* Moves the problem to the consumer of the `videojs-contrib-media-sources`

### Cons
* Means that the user of the `vjs-contrib-media-sources` project (ex. videojs-contrib-hls) must know about the codec used by the TS segments it is about to pass in. Simple enough with later version of HLS that mandate a CODEC parameter in the manifest.

## Solution 2
Parse the AAC `raw_data_block` to try to determine whether we are getting an HE-AAC or not and signal that to the consumer of the transmuxer to allow it to setup the MSE `sourceBuffer` correctly.

### Pros
* Transparent to the end user

### Cons
* Means that mux.js becomes important for the setup of `contrib-media-sources` which feels wrong
* Native m2ts support (Safari & Edge) likely require that the `codecs=` parameter is specified at `sourceBuffer` creation

**Comment by Pablo76** [comment]
chrome's impl for aac is buggy, and doesn't follow the spec, that's why instead of doing it once in c++ code in the browser, all kinds of messy js code to parse aac is required.
This isn't needed in FF and IE imo

**Comment by forbesjo** [comment]
Chrome will eventually fix this
