### ISSUE TITLE
Are there plans to support HEVC codec in the transmuxer?

### ISSUE THREAD

**Issue by avelad** [videojs/mux.js#423]
Many browsers are adding HEVC support if your HW supports it: https://caniuse.com/hevc

**Comment by gkatsev** [comment]
Unfortunately, probably not, at least not from the core team. This project is mostly meant for transmuxing ts into fmp4 and Apple doesn't officially support HEVC in ts segments.
However, if there's a PR for supporting it, we may accept it.

**Comment by avelad** [comment]
OK, thanks!
