### ISSUE TITLE
Fragment on keyframes

### ISSUE THREAD

**Issue by dmlap** [videojs/mux.js#45]
We currently generate mp4 fragments around flush() calls, which correspond to segment boundaries when the input in MPEG2-TS. This causes us to split GOPs, which means the later fragment is missing the reference frame and we have to drop some video data. If we fragmented on keyframes instead, we wouldn't have this problem.

**Comment by forbesjo** [comment]
@imbcmdth does GOP fusion fix this?

**Comment by forbesjo** [comment]
The answer was yes
