### ISSUE TITLE
Standalone MP4 fragmentation

### ISSUE THREAD

**Issue by chrisprobst** [videojs/mux.js#46]
Hi,

this is a great library, but currently it cannot be used for plain MP4 -> MSE fragmentation. (Am I wrong ?)

This is sad, since there is everything already in it, but the interface does not allow / support it.

Currently, there is only mp4box.js, which can do this but it cannot remux AV tracks into a single MP4 so you have to use multiple SourceBuffers... Bad for AV sync reason.

I'm not very experienced in this regard, so contributing is not so easy for me.

But I think the tasks are not very complicated:
- Make CoalesceStream public.
- Make it possible to get tracks from a MP4 buffer (complete file)
- Feed theses track objects to AudioSegmentStream and VideoSegmentStream
- Remux using CoalesceStream

So my interface of dream would be:
let fragmented = fragment(mp4Buffer);

Using events is fine, too. My Mp4 files are small (~5 seconds usually, P2P live video streaming).

I'm willing to contribute if you help me to get started.
This functionality is very important for !!!

Thanks in advance.

Kind regards,
Christopher

**Comment by forbesjo** [comment]
This is not currently on our roadmap but if you submit your changes we'll be happy to review them.

**Comment by nchavez324** [comment]
Hey forbesjo@, some comments seem to imply that this is possible today (from mp4box project pointing here: https://github.com/gpac/mp4box.js/issues/68#issuecomment-366190967).

Has this changed? Can mux.js fragment a non-fragmented mp4? If not, do you have any pointers to docs/sites I can use as reference for an implementation I'll later PR?

**Comment by ChrisChiasson** [comment]
@nchavez324 @forbesjo Or even without having docs, it would be helpful to just know if the answer to this is "yes" or "no". Mux.js is a large code base to go hunting for "unknown".
