### ISSUE TITLE
Wrong aspect ratio in Chrome

### ISSUE THREAD

**Issue by ntadej** [videojs/mux.js#62]
Aspect ratio is wrong on streams that don't have square pixels, but only on Chrome (tested on Win10 and OS X). It works as expected with Firefox and IE11 (on Win10).

I didn't want to duplicate bugs, but this is probably more related with mux.js than videojs-contrib-hls (opened as videojs/videojs-contrib-hls#485).

**Comment by aydinkn** [comment]
I have same problem with v1.3.8
Chrome result:
<img width="829" alt="screen shot 2016-02-18 at 11 46 12" src="https://cloud.githubusercontent.com/assets/5111036/13139746/b5c6b71e-d636-11e5-9e69-bfc722c60866.png">
Firefox result:
<img width="828" alt="screen shot 2016-02-18 at 11 45 49" src="https://cloud.githubusercontent.com/assets/5111036/13139755/c252abaa-d636-11e5-8850-4ab95731a074.png">

**Comment by forbesjo** [comment]
Could you link a sample video that we can use to debug this issue? Thanks

**Comment by aydinkn** [comment]
Here is the sample: http://codepen.io/anon/pen/RrmZqz

**Comment by aydinkn** [comment]
This problem not happened in hls.js. Any ideas?

**Comment by SteffenDE** [comment]
I can confirm it. In Safari and Firefox the sample works as expected, but in Chrome the aspect ratio is wrong. Using OS X 10.11.3.

**Comment by forbesjo** [comment]
Fixed with #83, closing
